version: '3'

services:
  php:
    build: './docker/php'
    volumes:
      - './app:/var/www/html'
    ports:
      - 5173:5173

  nginx:
    image: nginx:1.27.2
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  db:
    image: mysql:9.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/db/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8000:80